import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rajesh',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Suresh',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Forza Horizon 5',
      slug: 'forza-horizon',
      category: 'Racing',
      image: '/images/FORZA.jpg',
      price: 2589,
      countInStock: 10,
      brand: 'Playground Games',
      rating: 0,
      numReviews: 0,
      description: 'Realistic Racing Game',
    },
    {
      //_id: '2',
      name: 'Grand Theft Auto V',
      slug: 'grand-theft-auto-v',
      category: 'Action-Adventure',
      image: '/images/GTA.jpg',
      price: 2059,
      countInStock: 20,
      brand: 'Rockstar Games',
      rating: 0,
      numReviews: 0,
      description: 'Open-world crime and adventure game.',
    },
    {
      //_id: '3',
      name: 'Red Dead Redemption 2',
      slug: 'red-dead-redemption-2',
      category: 'Action-Adventure',
      image: '/images/RDR.jpg',
      price: 2199,
      countInStock: 25,
      brand: 'Rockstar Games',
      rating: 0,
      numReviews: 0,
      description:
        'Immerse yourself in the vast open-world of the American Wild West in this critically acclaimed action-adventure epic.',
    },
    {
      //_id: '4',
      name: 'FIFA 22',
      slug: 'fifa-22',
      category: 'Sports',
      image: '/images/FIFA.jpg',
      price: 1249,
      countInStock: 12,
      brand: 'EA Sports',
      rating: 0,
      numReviews: 0,
      description: 'Authentic football (soccer) simulation.',
    },
    {
      //_id: '5',
      name: "Assassin's Creed Origins",
      slug: 'assassins-creed-origins',
      category: 'Action RPG',
      image: '/images/ACO.jpg',
      price: 1099,
      countInStock: 18,
      brand: 'Ubisoft',
      rating: 0,
      numReviews: 0,
      description:
        "Embark on an epic journey in ancient Egypt as Bayek, the last of the Medjay, in this action RPG installment of the Assassin's Creed series.",
    },
    {
      //_id: '6',
      name: "Assassin's Creed Valhalla",
      slug: 'assassins-creed-valhalla',
      category: 'Action RPG',
      image: '/images/VALHALLA.jpg',
      price: 1849,
      countInStock: 18,
      brand: 'Ubisoft',
      rating: 0,
      numReviews: 0,
      description: 'Viking-themed action role-playing adventure.',
    },
    {
      //_id: '7',
      name: 'WWE 2K23',
      slug: 'wwe-2k23',
      category: 'Sports',
      image: '/images/JOHN.jpg',
      price: 2799,
      countInStock: 20,
      brand: '2K Sports',
      rating: 0,
      numReviews: 0,
      description:
        'Step into the squared circle and experience the excitement of professional wrestling with WWE 2K23, featuring realistic gameplay and a roster of your favorite WWE Superstars.',
    },
    {
      //_id: '8',
      name: 'DOOM',
      slug: 'doom',
      category: 'First-Person Shooter',
      image: '/images/DOOM.jpg',
      price: 1199,
      countInStock: 15,
      brand: 'id Software',
      rating: 0,
      numReviews: 0,
      description:
        'Rip and tear through hordes of demons in DOOM, an adrenaline-pumping first-person shooter that pushes the limits of speed and intensity.',
    },
    {
      //_id: '9',
      name: 'Rocket League',
      slug: 'rocket-league',
      category: 'Sports',
      image: '/images/RL.jpg',
      price: 1299,
      countInStock: 30,
      brand: 'Psyonix',
      rating: 0,
      numReviews: 0,
      description: 'Soccer but with rocket-powered cars.',
    },
    {
      //_id: '10',
      name: 'Dark Souls III',
      slug: 'dark-souls-iii',
      category: 'Action RPG',
      image: '/images/DARK.jpg',
      price: 2289,
      countInStock: 20,
      brand: 'Bandai Namco Entertainment',
      rating: 0,
      numReviews: 0,
      description: 'Challenging and atmospheric action role-playing game.',
    },
    {
      //_id: '11',
      name: 'Resident Evil Village',
      slug: 'resident-evil-village',
      category: 'Horror',
      image: '/images/RESIDENT.jpg',
      price: 2539,
      countInStock: 18,
      brand: 'Capcom',
      rating: 0,
      numReviews: 0,
      description: 'Survival horror set in a mysterious village.',
    },
    {
      //_id: '12',
      name: 'COD: MW2',
      slug: 'call-of-duty-modern-warfare',
      category: 'First-Person Shooter',
      image: '/images/COD.jpg',
      price: 6229,
      countInStock: 15,
      brand: 'Infinity Ward',
      rating: 0,
      numReviews: 0,
      description:
        'Intense and realistic first-person shooter with a gripping modern warfare storyline.',
    },
  ],
};

export default data;
