const data = {
  products: [
    {
      name: 'Forza Horizon 5',
      slug: 'forza-horizon',
      category: 'Racing',
      image: '/images/FORZA.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Playground Games',
      rating: 4.5,
      numReviews: 10,
      description: 'Realistic Racing Game',
    },
    {
      name: 'Grand Theft Auto V',
      slug: 'grand-theft-auto-v',
      category: 'Action-Adventure',
      image: '/images/GTA.jpg',
      price: 59.99,
      countInStock: 20,
      brand: 'Rockstar Games',
      rating: 4.8,
      numReviews: 25,
      description: 'Open-world crime and adventure game.',
    },
    {
      name: 'Red Dead Redemption 2',
      slug: 'red-dead-redemption-2',
      category: 'Action-Adventure',
      image: '/images/RDR.jpg',
      price: 59.99,
      countInStock: 25,
      brand: 'Rockstar Games',
      rating: 4.9,
      numReviews: 55,
      description:
        'Immerse yourself in the vast open-world of the American Wild West in this critically acclaimed action-adventure epic.',
    },
    {
      name: 'FIFA 22',
      slug: 'fifa-22',
      category: 'Sports',
      image: '/images/FIFA.jpg',
      price: 69.99,
      countInStock: 12,
      brand: 'EA Sports',
      rating: 4.6,
      numReviews: 22,
      description: 'Authentic football (soccer) simulation.',
    },
    {
      name: "Assassin's Creed Origins",
      slug: 'assassins-creed-origins',
      category: 'Action RPG',
      image: '/images/ACO.jpg',
      price: 49.99,
      countInStock: 18,
      brand: 'Ubisoft',
      rating: 4.7,
      numReviews: 40,
      description:
        "Embark on an epic journey in ancient Egypt as Bayek, the last of the Medjay, in this action RPG installment of the Assassin's Creed series.",
    },
    {
      name: "Assassin's Creed Valhalla",
      slug: 'assassins-creed-valhalla',
      category: 'Action RPG',
      image: '/images/VALHALLA.jpg',
      price: 54.99,
      countInStock: 18,
      brand: 'Ubisoft',
      rating: 4.7,
      numReviews: 28,
      description: 'Viking-themed action role-playing adventure.',
    },
    {
      name: 'WWE 2K23',
      slug: 'wwe-2k23',
      category: 'Sports',
      image: '/images/JOHN.jpg',
      price: 54.99,
      countInStock: 20,
      brand: '2K Sports',
      rating: 4.6,
      numReviews: 30,
      description:
        'Step into the squared circle and experience the excitement of professional wrestling with WWE 2K23, featuring realistic gameplay and a roster of your favorite WWE Superstars.',
    },
    {
      name: 'DOOM',
      slug: 'doom',
      category: 'First-Person Shooter',
      image: '/images/DOOM.jpg',
      price: 59.99,
      countInStock: 15,
      brand: 'id Software',
      rating: 4.9,
      numReviews: 50,
      description:
        'Rip and tear through hordes of demons in DOOM, an adrenaline-pumping first-person shooter that pushes the limits of speed and intensity.',
    },
    {
      name: 'Rocket League',
      slug: 'rocket-league',
      category: 'Sports',
      image: '/images/RL.jpg',
      price: 19.99,
      countInStock: 30,
      brand: 'Psyonix',
      rating: 4.5,
      numReviews: 15,
      description: 'Soccer but with rocket-powered cars.',
    },
    {
      name: 'Dark Souls III',
      slug: 'dark-souls-iii',
      category: 'Action RPG',
      image: '/images/DARK.jpg',
      price: 44.99,
      countInStock: 20,
      brand: 'Bandai Namco Entertainment',
      rating: 4.8,
      numReviews: 25,
      description: 'Challenging and atmospheric action role-playing game.',
    },
    {
      name: 'Resident Evil Village',
      slug: 'resident-evil-village',
      category: 'Horror',
      image: '/images/RESIDENT.jpg',
      price: 54.99,
      countInStock: 18,
      brand: 'Capcom',
      rating: 4.7,
      numReviews: 30,
      description: 'Survival horror set in a mysterious village.',
    },
    {
      name: 'COD: MW2',
      slug: 'call-of-duty-modern-warfare',
      category: 'First-Person Shooter',
      image: '/images/COD.jpg',
      price: 59.99,
      countInStock: 15,
      brand: 'Infinity Ward',
      rating: 4.8,
      numReviews: 50,
      description:
        'Intense and realistic first-person shooter with a gripping modern warfare storyline.',
    },
  ],
};
export default data;
